mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mirror?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Modoojunko#123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    dateFormat: yyyy-MM-dd HH:mm:ss

server:
  port: 8080
  servlet:
    context-path: /mirror

logging:
  level:
    com:
      priv:
        gabriel:
          demoformybatis:
            mapper: debug